config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :todos do
    member do
      put :complete
    end
    member do
      put :uncomplete
    end
  end

  resources :users do
    resources :todos
    resources :user_roles
  end

  resources :roles do
    resources :user_roles
  end

  resources :user_roles do
  end

  get 'welcome/index'

  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

    user ||= User.new
    if user.role? :admin
        can :manage, :all
    else
        can :read, :all
        can :create, Todo
        can :complete, Todo
        can :uncomplete, Todo
    end
  end
end

app/models/todo.rb
	class Todo < ActiveRecord::Base
		belongs_to :user
	end

app/models/user.rb
  class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable

    has_many :todos

    ROLES = %w[admin user]

    def roles=(roles)
      self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
    end

    def roles
      ROLES.reject do |r|
        ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
      end
    end

    def role?(role) 
      roles.include?(role.to_s)
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception|
  	flash[:error] = "Access denied."
  	redirect_to root_url
  end
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:email, :password, :password_confirmation, :current_password, roles: [])}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:email, :password, :password_confirmation, :current_password, roles: [])}

  end

  layout 'flatly'
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  # load_and_authorize_resource

  before_action :set_todo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.where(completed: false)
    @completes = Todo.where(completed: true)
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # GET /todos/1/complete
  def complete
    @todo = Todo.find(params[:id])

    respond_to do |format|
      if @todo.update_attribute(:completed, true)
        format.html { redirect_to todos_url, notice: 'To-Do was successfully updated.' }
        format.json { render :show, status: :ok, location: todos_url}

      else
        format.html { redirect_to @todo, notice: 'To-Do was not updated... Is it already done???' }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /todos/1/uncomplete
  def uncomplete
    @todo = Todo.find(params[:id])

    respond_to do |format|
      if @todo.update_attribute(:completed, false)
        format.html { redirect_to todos_url, notice: 'To-Do was successfully updated.' }
        format.json { render :show, status: :ok, location: todos_url }

      else
        format.html { redirect_to todos_url, notice: 'To-Do was not updated... Is it already done???' }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)
    @todo.user_id = current_user.id
    
    respond_to do |format|
      if @todo.save
        format.html { redirect_to todos_url, notice: 'To-Do was successfully created.' }
        format.json { render :show, status: :created, location: todos_url }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todos_url, notice: 'To-Do was successfully updated.' }
        format.json { render :show, status: :ok, location: todos_url }

      elsif false #This will never happen as the user cannot edit for now.
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }

      else
        format.html { redirect_to @todo, notice: 'To-Do was not updated... Is it already done???' }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'To-Do was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:name, :completed)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	if user_signed_in?
  		redirect_to :controller => 'todos', :action => 'index'
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_user_widget.html.erb
<% if user_signed_in? %>
  <p>Welcome <%= current_user.email %></p>
  <%= link_to 'Logged In [click to logout]', destroy_user_session_path, :method => :delete %>
<% else %>
  <p>You are not signed in.</p>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<%= render "shared/header" %>

<%= yield %>

<%= render "shared/footer" %>

app/views/layouts/flatly.html.erb
<%= render "shared/header" %>

    <div class="container theme-showcase">

      <% flash.each do |name, message| %>
        <div class="alert alert-info">
            <%= content_tag :div, "Status: " + message, :id => "flash_#{name}" %>
        </div>
      <%end%>

      <%= yield %>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "flatly" %>
    <%= yield(:page_javascript) if content_for?(:page_javascript) %>

<%= render "shared/footer" %>

app/views/shared/_footer.html.erb
  </body>
</html>

app/views/shared/_header.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "To-Do List" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "flatly", :media => "all" %>

    <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.2.0/simplex/bootstrap.min.css" rel="stylesheet">
    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

  </head>
  <body>

    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">To Do List</a>
        </div>
        
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">Home</a></li>
            
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="<%= edit_user_registration_path %>">Edit Profile</a></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            
            <% else %>
              <li><a href="<%= new_user_registration_path %>">Sign Up</a></li>
              <li><a href="<%= new_user_session_path %>">Login</a></li>
            <% end %>

          </ul>
          
          <% if user_signed_in? %>
            <div class="navbar-text pull-left">
                Logged in as <strong><%= current_user.email %></strong>. 
            </div>
          <% end %>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
    <%= f.hidden_field :completed, :value => false %>
  </div>

  <div class="field">
    <%= f.label :completed %><br>
    <%= f.check_box :completed %>
  </div>
  
<br>

  <div class="actions">
    <%= f.submit class: "btn btn-sm btn-default"%>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<br>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<div>
  <%= link_to 'Add a new To-Do', new_todo_path, class: "btn btn-primary" %>
</div>

<br>

<div class="col-sm-12">
  <% if !@todos.empty? %>
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">To-Do</h3>
      </div>
      <div class="panel-body">
        <table>
          <tbody>
            <% @todos.each do |todo| %>
              <% if todo.user_id == current_user.id%>
                <tr>
                  <td><strong><%= todo.name %></strong></td>
                </tr>
                <tr>
                  <td><%= link_to 'Mark Completed', complete_todo_path(todo), class: "btn btn-xs btn-link", :method => :put %>
                  - <%= link_to 'Show', todo, class: "btn btn-xs btn-link" %>
                  <% if can? :update, @todo %>
                    - <%= link_to 'Edit', edit_todo_path(todo),  class: "btn btn-xs btn-link" %>
                  <% end %>
                  - <%= link_to 'Remove', todo,  class: "btn btn-xs btn-link", method: :delete, data: { confirm: 'Are you sure you want to remove this item?' } %></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>

  <% if !@completes.empty? %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Completed</h3>
      </div>
      <div class="panel-body">
        <table>
          <tbody>
            <% @completes.each do |todo| %>
              <% if todo.user_id == current_user.id%>
                <tr>
                  <td><strong><%= todo.name %></strong></td>
                </tr>
                <tr>
                  <td><%= link_to 'Mark Incompleted', uncomplete_todo_path(todo), class: "btn btn-xs btn-link", :method => :put %>
                  - <%= link_to 'Show', todo, class: "btn btn-xs btn-link" %>
                  <% if can? :update, @todo %>
                    - <%= link_to 'Edit', edit_todo_path(todo),  class: "btn btn-xs btn-link" %>
                  <% end %>
                  - <%= link_to 'Remove', todo,  class: "btn btn-xs btn-link", method: :delete, data: { confirm: 'Are you sure you want to remove this item?' } %></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>
</div><!-- /.col-sm-12 -->

app/views/todos/new.html.erb
<h1>New To-Do</h1>

<%= render 'form' %>

<br>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @todo.name %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @todo.completed %>
</p>

<% if can? :update, @todo %>
  <%= link_to 'Edit', edit_todo_path(@todo) %> | 
<% end %>
<%= link_to 'Back', todos_path %>

app/views/welcome/index.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
	<h1>Welcome to the To Do List App</h1>
	
	<p>I'm building a simple to-do list application in hopes of filling it with more to-do's as a Web Dev ;-)  This app will be submitted to Codecademy in hopes of exploring employment oppportunities as a Web Dev.</p>

	<%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-primary btn-lg" %>
</div>